apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: es-ocp-e2e

resources:
  - namespace.yaml
  - cluster.yaml

commonLabels:
  app.kubernetes.io/part-of: es-ocp-e2e
  app.kubernetes.io/component: elasticsearch
  app.kubernetes.io/managed-by: eck
