apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: es-aks-e2e-production
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: es-aks-e2e
  path: ./overlays/production
  prune: true
  wait: true
  timeout: 5m
