apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: es-ocp-e2e

resources:
  - rbac.yaml
  - fleet-server.yaml
  - elastic-agent.yaml

commonLabels:
  app.kubernetes.io/part-of: es-ocp-e2e
  app.kubernetes.io/component: agents
  app.kubernetes.io/managed-by: eck
