apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: es-aks-e2e-dev
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: es-aks-e2e
  path: ./overlays/dev
  prune: true
  wait: true
  timeout: 2m
